#  Copyright 2020 ThoughtWorks, Inc.
#  
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#  
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/agpl-3.0.txt>.
grid:
   uri: /projects/mingle/cards/grid?color_by=priority&filters[]=[type][is][story]&filters[]=[release][is][1.1]&group_by=story+status
list:
  uri: /projects/mingle/cards/list?columns=feature&filters[]=%5Btype%5D%5Bis%5D%5Bbug%5D&filters[]=%5Bbug+status%5D%5Bis%5D%5Bfixed%5D